### ISSUE TITLE
Error message.

### ISSUE THREAD

**Issue by shinexo** [kagikn/JPNPatchSA#1]
Hello. I've done all the instalation normally, I'm running the 1.01 EU version and I've got this error message when trying to boot the game. Could you help me please?

![Screenshot_269](https://user-images.githubusercontent.com/63097036/120803005-730cb900-c519-11eb-8dd4-302bcfa2d9b6.png)

**Comment by shinexo** [comment]
I also tried to replace the data/models folder and the gtx file that (i think) you've provided but then it looks like this.
![Screenshot 2021-06-04 12-26-31](https://user-images.githubusercontent.com/63097036/120825826-297b9880-c530-11eb-9c8a-e1b21b2c000d.png)
(this without the asi script)

**Comment by kagikn** [comment]
Could you tell me the exact file size of your gta_sa.exe in bytes?
I guess version detection of the ASI is not working for 1.01 EU version properly, but I should check if your exe is really 1.01 EU version (or actually old Steam version).

**Comment by shinexo** [comment]
15,806,464
![Screenshot_270](https://user-images.githubusercontent.com/63097036/120898590-da9e3380-c601-11eb-9ce0-51d167482e80.png)
At least it was suposed to be, because when I downgraded the game It was what i opted for. If it isnt then I dont know...

**Comment by kagikn** [comment]
You're correct. Your exe is indeed 1.01 EU version.
Changing this line:
https://github.com/kagikn/JPNPatchSA/blob/bdad71fef82203e966be7b1cee68c1205316ef0d/JPNPatchSA/JPNPatchSA.cpp#L21
To `if (*reinterpret_cast<unsigned int*>(0x40104C) == 0x50EC83EC)` fixes version detection problem, but I need to investigate if this mod really works with 1.01 EU exe.
The the game (1.01 EU) crashes every time it tries to draw texts with this ASI, so I think the ASI patches 1.01 EU version wrong.

**Comment by kagikn** [comment]
Now the ASI will work in 1.01. Corrected target addresses to patch for 1.01 EU exe.
